name: Documentation

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['website/**', '.github/workflows/pages.yml']

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      artifact_name: github-pages-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: website/package-lock.json
      - run: npm ci
        working-directory: website
      - run: npm run build
        working-directory: website
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          name: github-pages-${{ github.run_attempt }}
          path: website/dist

  deploy:
    if: vars.PAGES_ENABLED == 'true'
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        id: deployment
        with:
          artifact_name: ${{ needs.build.outputs.artifact_name }}
